version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: desafio_postgres
    restart: always
    environment:
      POSTGRES_DB: desafio
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: desafio_backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/desafio
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      JWT_SECRET_KEY: MINHA_CHAVE_SECRETA_AQUI_TROQUE_POR_UMA_MAIS_SEGURA
    env_file:
      - .env
    volumes:
      - ./backend:/app
    command: ["./mvnw", "spring-boot:run"]

volumes:
  postgres_data:
